<?php

namespace App\Filament\Resources\PhotoBatchResource\RelationManagers;

use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\RelationManagers\RelationManager;
use Filament\Tables;
use Filament\Tables\Table;
use App\Models\PhotoBatch;
use Filament\Notifications\Notification;

class EbayShopifyRelationManager extends RelationManager
{
    protected static string $relationship = 'batch'; // Dummy relationship

    protected static ?string $title = 'eBay & Shopify';

    protected static ?string $label = 'eBay & Shopify';

    protected static ?string $recordTitleAttribute = null;

    public function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\Section::make('Product Listing - eBay & Shopify')
                    ->description('Create SEO-optimized listings for eBay and Shopify marketplaces')
                    ->schema([
                        Forms\Components\Grid::make(2)
                            ->schema([
                                Forms\Components\TextInput::make('ebay_title')
                                    ->label('Title (English)')
                                    ->placeholder('e.g., Vintage Nike Air Max 90 Running Shoes')
                                    ->maxLength(80)
                                    ->helperText('Max 80 characters for eBay')
                                    ->suffixAction(
                                        Forms\Components\Actions\Action::make('generate_title')
                                            ->icon('heroicon-o-sparkles')
                                            ->action(function (Forms\Set $set, Forms\Get $get) {
                                                Notification::make()
                                                    ->title('Generating title with Gemini...')
                                                    ->info()
                                                    ->send();
                                                // TODO: Call Gemini API
                                            })
                                    ),

                                Forms\Components\Select::make('ebay_condition')
                                    ->label('Condition')
                                    ->options([
                                        'New with tags' => 'New with tags',
                                        'New without tags' => 'New without tags',
                                        'Pre-owned - Excellent' => 'Pre-owned - Excellent',
                                        'Pre-owned - Good' => 'Pre-owned - Good',
                                        'Pre-owned - Fair' => 'Pre-owned - Fair',
                                    ])
                                    ->default('Pre-owned - Good')
                                    ->required(),
                            ]),

                        Forms\Components\Textarea::make('ebay_description')
                            ->label('Description (English)')
                            ->rows(8)
                            ->placeholder('Detailed product description...')
                            ->helperText('SEO-optimized description will be generated by AI')
                            ->suffixAction(
                                Forms\Components\Actions\Action::make('generate_description')
                                    ->icon('heroicon-o-sparkles')
                                    ->action(function (Forms\Set $set, Forms\Get $get) {
                                        Notification::make()
                                            ->title('Generating description with Gemini...')
                                            ->info()
                                            ->send();
                                        // TODO: Call Gemini API
                                    })
                            ),

                        Forms\Components\Grid::make(3)
                            ->schema([
                                Forms\Components\TextInput::make('ebay_brand')
                                    ->label('Brand')
                                    ->placeholder('e.g., Nike'),

                                Forms\Components\TextInput::make('ebay_size')
                                    ->label('Size')
                                    ->placeholder('e.g., L, 42, 10 US'),

                                Forms\Components\TextInput::make('ebay_color')
                                    ->label('Color')
                                    ->placeholder('e.g., Black, Blue'),
                            ]),

                        Forms\Components\Grid::make(2)
                            ->schema([
                                Forms\Components\TextInput::make('ebay_price')
                                    ->label('Price (USD)')
                                    ->numeric()
                                    ->prefix('$')
                                    ->default(0),

                                Forms\Components\Select::make('ebay_category')
                                    ->label('eBay Category')
                                    ->searchable()
                                    ->options([
                                        'Clothing, Shoes & Accessories' => 'Clothing, Shoes & Accessories',
                                        'Men\'s Clothing' => 'Men\'s Clothing',
                                        'Women\'s Clothing' => 'Women\'s Clothing',
                                        'Shoes' => 'Shoes',
                                        'Bags & Accessories' => 'Bags & Accessories',
                                    ])
                                    ->default('Clothing, Shoes & Accessories'),
                            ]),

                        Forms\Components\TagsInput::make('ebay_tags')
                            ->label('Tags / Keywords')
                            ->placeholder('vintage, retro, nike, running')
                            ->helperText('SEO keywords for better visibility'),
                    ]),

                Forms\Components\Section::make('Similar Products')
                    ->description('Copy listings from similar products in your inventory')
                    ->schema([
                        Forms\Components\View::make('filament.forms.components.similar-products')
                            ->viewData([
                                'record' => $this->getOwnerRecord(),
                            ]),
                    ])
                    ->collapsible()
                    ->collapsed(),
            ]);
    }

    public function table(Table $table): Table
    {
        // We don't want to show a table, just a form
        return $table
            ->recordTitleAttribute('id')
            ->columns([])
            ->headerActions([])
            ->actions([])
            ->emptyStateHeading('eBay & Shopify Integration')
            ->emptyStateDescription('Use the form above to create optimized listings');
    }

    public static function canViewForRecord(\Illuminate\Database\Eloquent\Model $ownerRecord, string $pageClass): bool
    {
        return true;
    }
}
